name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: sumanthegdedocker
        run: sudo docker pull sumanthegdedocker/obesity_risk:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f obesity_risk-container || true

      - name: Run Docker Container
        env:
          DOCKER_USER: sumanthegdedocker
        run: sudo docker run -it -d -p 8001:8001 --name obesity_risk-container sumanthegdedocker/obesity_risk:latest