name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    -  name: Checkout Code
       uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python model_training/train_pipeline.py
    - uses: actions/upload-artifact@v2
      with:
        name: my-trained-pipeline
        path: model_training/trained_models/*.pkl
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: model_training/trained_models
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: model_training/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
        path: model_api

    - name: Login to Docker hub
      env:
        DOCKER_USER: sumanthegdedocker
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: sumanthegdedocker
      run: docker build . -f Dockerfile -t $DOCKER_USER/obesity_risk:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: sumanthegdedocker
      run: docker push $DOCKER_USER/obesity_risk-fastapi

    - name: Logout to Docker hub
      run: docker logout
